---
title: "BSMix Simulations"
author: "Alex Dombowsky"
date: '2022-05-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(splines)
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
```

In which I do some simulations for the BSMix method.

# Example 1: GaussGamma

## Write Functions
```{r}
# sample 2 component GMM
univar.twocomp.GMM<- function(n, p, mu, sigma) {
  # p = probablity of being in cluster 1
  # mu, sigma = component normals
  s <- rbinom(n = n, size = 1, prob = p)
  x <- s * rnorm(n, mean = mu[1], sd = sigma[1]) + (1 - s) * rnorm(n = n, mean = mu[2], sd = sigma[2])
  return(x)
}

# sample Gauss Gamma
univar.GaussGamma <- function(n, omega, p_mix, mu_mix, sigma_mix, mu, sigma, shape, rate){
  # omega = vector of probabilties for mixture
  # p_mix, mu_mix, sigma_mix = parameters for 2 component mixture
  # mu, sigma = normal parameters
  # shape, rate = gamma parameters
  
  K <- 4
  s <- sample(1:K, size = n, replace = T, prob = omega)
  x <- c()
  for (i in 1:n){
    if (s[i]==1){
      x[i] <- univar.twocomp.GMM(n = 1, p = p_mix, mu = mu_mix, sigma = sigma_mix)
    }
    else if (s[i] == 2){
      x[i] <- rnorm(n = 1, mean = mu[1], sd = sigma[1])
    }
    else if (s[i] == 3) {
      x[i] <- rnorm(n = 1, mean = mu[2], sd = sigma[2])
    }
    else {
      x[i] <- rgamma(n = 1, shape = shape, rate = rate)
    }
  }
  return(list(data = x, s = s))
}


```

## Now, Implement
```{r}
gg_data <- univar.GaussGamma(n = 5000,
                             omega = c(0.4, 0.2, 0.2, 0.2),
                             p_mix = 0.6,
                             mu_mix = c(-10, -6),
                             sigma_mix = c(1,1),
                             mu = c(-0.5,5),
                             sigma = c(0.1, 0.1),
                             shape = 20,
                             rate = 2)
gg_s <- gg_data$s
gg_data <- gg_data$data

gg_data <- data.frame(data = gg_data)
gg_data %>%
  ggplot(aes(x = data)) + geom_density() + labs(title = "Density of the Data")

```

## Now, fit with BGMM
```{r}
source("rfuncts/norm.BGMM.gibbs.R")
R <- 20000
L <- 100
y <- gg_data$data
pars <- c(0,1,10,25)
priors <- matrix(rep(pars, L), nrow = L, byrow = T)
priors <- cbind(priors, 1:L)
# fitting
fit <- ugmm.overfitted.gibbs(R = R,
                             L = L,
                             y = y,
                             priors = priors,
                             alpha = rep(1,L),
                             stops = 500)

```

## Cluster the Densities
```{r}
source("rfuncts/unorm.cluster.R")
source("rfuncts/unorm.D.R")
source("rfuncts/unorm.hellinger.R")


# extracting
B <- 10000 # burnin
mu <- fit$mu[-(1:B), ]
sigma <- sqrt(fit$sigma_sq)[-(1:B), ]
omega <- fit$omega[-(1:B), ]
pars <- cbind(mu, sigma)

# labeling
dens_clusters <- apply(pars, 1, unorm.cluster, L = L, K = 4)
dens_clusters <- t(dens_clusters)
```

## Re-Normalize Mixtures

```{r}
source("rfuncts/unorm.renormalize.R")
mcmc_samps <- cbind(mu, sigma, omega, dens_clusters)
new_mixtures <- apply(mcmc_samps, 1, unorm.renormalize, L = L, K = 4) # produces list of length R
# each element of List is a list of 2 things: the first is renormalized mixtures, the second is renormalized weights

```


## Classify Data

```{r}
source("rfuncts/bayesrule_cluster.R")
# debugging
new_mixtures_db <- new_mixtures[1:100]
a = Sys.time()
cluster_list_db <- lapply(new_mixtures_db, bayesrule_cluster, y = y, K = 4)
b = Sys.time()
b - a
cluster_matrix_db <- do.call(rbind, cluster_list_db)

cluster_list <- lapply(new_mixtures, bayesrule_cluster, y = y, K = 4)
cluster_matrix <- do.call(rbind, cluster_list)

```


## Do W&G
```{r}
library(mcclust)
library(mcclust.ext)
c.psm <- comp.psm(cluster_matrix_db)
c.mv <- minVI(psm = c.psm,
              cls.draw = cluster_matrix_db,
              max.k = 4)

```


## Compare to the Original Clustering
```{r}
library(mclust)
adjustedRandIndex(gg_s, c.mv$cl)
```

## plot the clustering with data
```{r}
cluster.df <- data.frame(reference = rep(0, length(gg_data)),
                         data = gg_data,
                         cl = factor(c.mv$cl), 
                         s = factor(gg_s))


p1 = cluster.df %>% ggplot(aes(x = data)) + geom_density() + 
  geom_point(data = cluster.df, aes(x = data, y = reference, color = cl)) +
  labs(title = "Estimated Clusters")

p2 = cluster.df %>% ggplot(aes(x = data)) + geom_density() + 
  geom_point(data = cluster.df, aes(x = data, y = reference, color = s)) +
  labs(title = "True Clusters")

grid.arrange(p1, p2, nrow = 1)

```


# Example 2: Generate From Splines
* from https://www.r-bloggers.com/2017/10/can-we-use-b-splines-to-generate-non-linear-data/
```{r}
genSpline <- function(x, knots, degree, theta) {
  basis <- bs(x = x, knots = knots, degree = degree,
              Boundary.knots = c(0,1), intercept = TRUE)
  y.spline <- basis %*% theta
  dt <- data.frame(x, y.spline = as.vector(y.spline))
  return(list(dt = dt, basis = basis, knots = knots))
}
```

